version: '3.7'
services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/todo_db?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - '3306'
    networks:
      - springapimysql-net
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
networks:
  springapimysql-net: