spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: "jdbc:mysql://localhost:3306/todo_db"
    driverClassName: "com.mysql.jdbc.Driver"
    username: "root"
    password: "root"
    jpa:
      show-sql: true
      database-platform: "org.hibernate.dialect.MySQL8Dialect"
      defer-datasource-initialization: true
      generate-ddl: true
      hibernate:
        ddl-auto: update