DROP TABLE IF EXISTS todos;
CREATE TABLE  todos (
  todo_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) DEFAULT NULL

);
DROP TABLE IF EXISTS tasks;
CREATE TABLE tasks (
	task_id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255) DEFAULT NULL,
	todo_id INT,
	FOREIGN KEY (todo_id) REFERENCES todos(todo_id) ON DELETE SET NULL
);